### PR TITLE
signals: Add standard signal handling

### LINKED ISSUE #32: Implement standard signal and crash handling behaviour
Add standard signal handling behaviour:

- backtrace on internal error or fatal signal and exit.
- core dump on internal error or fatal signal if debug enabled.
- backtrace on `SIGUSR1` if debug enabled but continue to run.

For example, see:

- https://github.com/clearcontainers/runtime/pull/1054
- https://github.com/kata-containers/runtime/pull/244

### PR DESCRIPTION
**Pull request by jodh-intel**
Add the standard project signal handling. However, since it needs to be
applied to two different binaries, encapsulate it in a new package.

Fixes #32.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Blocked on #40 - I need to rework the logging calls on this PR and remove the FIXME's once #40 has landed.

**Comment by jodh-intel** [comment]
Still waiting for #40 to be merged....

**Comment by jodh-intel** [comment]
Branch ready for review.

File: trigger/virtcontainers/vc.go [hunk 1]
```diff
@@ -7,16 +7,20 @@
 package main
```
Comment (grahamwhaley) [inline trigger/virtcontainers/vc.go]: Update copyright?

Comment (jodh-intel) [reply trigger/virtcontainers/vc.go]: Fixed.

**Comment by grahamwhaley** [comment]
@jodh-intel - did you reply to my codecov query (sorry if you did, I don't think I saw a reply). I suspect it is an understood issue, and we can ignore it - so we'd just need the extra ack from somebody in @kata-containers/throttler ...

**Comment by jodh-intel** [comment]
Ping y'all!
